### ISSUE TITLE
hl-line hides the region (when active)

### ISSUE THREAD

**Issue by sebasmonia** [cstby/solo-jazz-emacs-theme#1]
If you enable hl-line, and then select say, the word under point, you can't really see the selection, because they use the same color.

![image](https://user-images.githubusercontent.com/1651857/92332680-da561500-f03c-11ea-8d2f-37456f5706b8.png)

In the image above, the region is up to the `r` only but since the color for hl-line and active region is the same, it gives the impression the whole line is selected.

Awesome theme, it's a breath of fresh air IMO. Thank you!

**Comment by cstby** [comment]
Glad to hear you're enjojying the theme, and thanks for opening this issue!

I added support for hl-line on a new branch called `hl-line`. I decided to go with a brighter, subtler highlight. Check it out and let me know what you think? I'll probably play around with it for a few days before merging that branch into master.

**Comment by sebasmonia** [comment]
It's an improvement for sure! 
I'm testing it too. It might be too subtle? That's just a first impression.

**Comment by cstby** [comment]
I agree, although at first it seemed adequate because I haven't used `hl-line` in a while.

I've experimented with a few different approaoches and ended up making a new light shade of teal. The other appraoches would require non-trivial work. (I realize now that I should have saved some screenshots to demonstrate what I'm about to explain.)

-   I tried splitting the current light-purple color into a shaded version (for selected) and a tinted version (for hl-line). The result was only a very subtle contrast between the highlighted line and selected text. Widening the difference betwen the colors resulting in the current highlight face being too dark in the places it's curerntly used. This approach would require reassesing which of the two (or three) new colors to use in each case, and then likely some more adjusting.
- I also tried using a darker neutral color for hl-line. This also resulted in a too subtle of a contrast between the hl-line color and selected text. It also felt a little too heavy aesthetically. It might be possible to use a darker non-neutral color, but this would also take some time to uncover.

My current thought is that the teal color fits the them and provides adequate contrast against the background and color for selected text.

EDIT: I should have been more explicit above. I pushed this changed to the `hl-branch`.

**Comment by sebasmonia** [comment]
I like this one a lot more than the previous change. For a second it was a bit jarring, but then as I scroll around the text the hl-line color feels natural.

Thank you for taking the time to experiment until you found the best way to handle this!
As far as I'm concerned this one is a winner.

**Comment by cstby** [comment]
Excellent. I've mereged these changes into `master` and referenced this issue in the commit. I'm going to close this out and add to my personal backlog to explore the approaches mentioned above.
