### ISSUE TITLE
Better compatibility with show-paren-mode

### ISSUE THREAD

**Issue by sebasmonia** [cstby/solo-jazz-emacs-theme#9]
When activating show-paren-mode, when point is the opening parenthesis, the way the highlight works is makes it appear as if it moved to the end of pair, example:

![image](https://user-images.githubusercontent.com/1651857/134594301-5929b986-1f56-4c38-9140-6eafd5e7d921.png)
Point is on `[`, and actually before taking the focus away for the screenshot, the opening bracket didn't look highlighted.

**Comment by sebasmonia** [comment]
Took a picture with my phone (yay technology!) that shows the issue even better, here point is in the opening parenthesis: 
![image](https://user-images.githubusercontent.com/1651857/134594956-df70766b-e91f-412a-ad83-fc3f6e751f77.png)

My config:
```
(use-package paren
  :ensure nil
  :config
  (show-paren-mode)
  :custom
  (show-paren-style 'mixed))
```

**Comment by cstby** [comment]
Thanks for pointing this out. The underlying problem here is that the `cursor` face is the the same as `show-paren-match`. I've pushed a fix to the master branch that changes the show-paren face to blue. This might be too subtle a difference from the teal cursor, so I plan to try out a few colors over the next few weeks before settling on one.

**Comment by sebasmonia** [comment]
Just tested the change and it makes the package usable with show-paren, thank you!

Maybe keeping everything under point the same, and highlighting with a softer color the "other" paren/bracket/etc. would work too.

**Comment by cstby** [comment]
Updated the `show-paren` faces to be even more distinct from the cursor.
